### ISSUE TITLE
Example of template.genie and thingpedia.tt

### ISSUE THREAD

**Issue by kenyeung128** [stanford-oval/genie-toolkit#122]
Hi, in the docs, it shows how to synthesize a set of sentences using

genie generate --locale en --template template.genie
  --thingpedia thingpedia.tt --entities entities.json --dataset dataset.tt
  -o synthesized.tsv

however, is there an example template.genie and thingpedia.tt how it looks like?

**Comment by gcampax** [comment]
Hi @kenyeung128 ! Thanks for the question.

`thingpedia.tt` can be downloaded using the `download-snapshot` command, or from the [Thingpedia API](https://almond.stanford.edu/doc/thingpedia-api/) or the [thingpedia-cli](http://npmjs.com/thingpedia-cli) command line tool.
Templates are in the `languages/` folder of this repository.
