### ISSUE TITLE
Run In Google Colab:

### ISSUE THREAD

**Issue by zbush548** [stanford-oval/genie-toolkit#188]
[https://github.com/stanford-oval/genie-toolkit/blob/55689fb105cb1cd0ee0d3fd85313af8668b1585b/tool/lib/bert-canonical-annotator.py](url)

When I run the script in Google Colab, I find myself on the receiving end of this error. Could you please direct me on how to fix this?

```
usage: ipykernel_launcher.py [-h] [--mask] [--no-mask]
                             [--k-synonyms K_SYNONYMS]
                             [--k-adjectives K_ADJECTIVES]
                             [--pruning-threshold PRUNING_THRESHOLD]
                             [--model-name-or-path MODEL_NAME_OR_PATH]
                             [--is-paraphraser] [--gpt2-ordering]
                             {adjectives,synonyms,all}
ipykernel_launcher.py: error: argument command: invalid choice: '/root/.local/share/jupyter/runtime/kernel-65147072-f648-4150-b77f-34e68cd44dfb.json' (choose from 'adjectives', 'synonyms', 'all')
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by gcampax** [comment]
The Python script you run is not meant to be run directly.
Instead, you should call "genie autogen-annotations". You can call this command on any Thingpedia manifest file, and the output is another Thingpedia manifest file with additional annotations. The wrapper code takes care of formatting the inputs and outputs to the Python scripts correctly.
Does it make sense?

**Comment by zbush548** [comment]
Thank you. I'm new to coding, but I'll be sure to try what you suggested.

**Comment by gcampax** [comment]
Well, if you're new to Genie, I would suggest reading our docs first. Start at <https://almond.stanford.edu/doc/genie-intro.md>, as well as the readme in this repo.
We also have a couple of short tutorials at https://github.com/stanford-oval/cs294-homework-workdir, with some scaffolding code that makes setup easier. They are written as homework assignments for a class we ran at Stanford, but they should be followable by the general public.

**Comment by zbush548** [comment]
Thank you. I really appreciate it.

**Comment by gcampax** [comment]
Great, if there is nothing left here, I'm going to close this.
