### ISSUE TITLE
Errors while trying to train

### ISSUE THREAD

**Issue by yuvaldolev** [stanford-oval/genie-toolkit#22]
Hi, I'm trying to train a model to reproduce the results of the PLDI 2019 paper. If followed the instructions in the "Reproducing the results the PLDI 2019 paper" page and I downloaded the dataset, but when I started training using the ```genie train --datadir dataset --outputdir model --workdir temp --config-file data/full.json``` commad, I got the following error:
```
  0%  [..............................] - ETA: 0s/Users/user/.config/yarn/global/node_modules/genie-toolkit/tool/genie.js:13
process.on('unhandledRejection', (up) => { throw up; });

Error: Command exited with code 2
    at ChildProcess.child.on (/Users/user/.config/yarn/global/node_modules/genie-toolkit/lib/training/exec-utils.js:37:28)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```
Did I do something wrong?
Thanks!

**Comment by gcampax** [comment]
I am not sure what the error indicates (you should use `--debug` to see exactly what fails), but in any case, if you're reproducing the paper, make sure you are using exactly version `v0.1.1` of genie-toolkit, and make sure to follow the installation instructions in the main readme.

**Comment by yuvaldolev** [comment]
OK,
Thank you.

**Comment by gcampax** [comment]
As there were no further comments, I'm assuming it works now. Closing, please reopen if it is not the case.
