### ISSUE TITLE
Review Request: Traditional Chinese Dataset

### ISSUE THREAD

**Issue by elvisyjlin** [stanford-oval/genie-toolkit#24]
Hi all,

I've made a small Traditional Chinese dataset, which contains 110+ utterances. And I ran the synthetic sentence generation on it. For those who understand Chinese, please have a look here (https://goo.gl/PeoWuY).
* `dataset.zh-tw.part0.tt` is the Traditional Chinese dataset.
* `synthetic.zh-tw.part0.tsv` is the synthetic sentences.

The translation of all sentences will be continued in the following days.

**Comment by gcampax** [comment]
I can't comment on the actual chinese, but I found a couple of problems:
- there is an Almond with capital A in the templates; that should be lowercase because all latin characters are lowercased by the tokenizer
- there are a couple of segmentation problems: "從kanye west", "instagram時", "當google drive", maybe more
- enum values are still in English, and that won't do; we need code to translate them

**Comment by elvisyjlin** [comment]
* I can't see a sentence with _Almond_ in `preprocessed` sentences.
* I deem that the CoreNLP doesn't work well in Traditional Chinese. For instance, I tried this case on http://corenlp.run
  * In TC: `當我上傳照片到instagram時` -> `當我 上 傳 照片 到 instagram時`
  * In SC: `当我上传照片到instagram时` -> `当 我 上传 照片 到 instagram 时`
  A workaround solution is convert utterances  from Traditional Chinese to Simplified Chinese once Genie reads them from a Traditional Chinese dataset.
* We can either declare Chinese enum value in dataset or translate English enum values when filling them in the synthetic sentences. Which way do you think is better?

**Comment by elvisyjlin** [comment]
I've surveyed some tools to convert Chinese characters.
* OpenCC (https://github.com/BYVoid/OpenCC) seems to be the most popular Chinese convertor. It is available in nodejs while the backend is built with C.
* node-opencc (https://github.com/compulim/node-opencc) is another project which mimic OpenCC and is written in pure js.

**Comment by gcampax** [comment]
`Almond` is probably in the construct templates (genie files)
Declaring Chinese enums in the dataset will not work, because the API still expects the English enum value so it would not typecheck.
As for the segmentation issue, one workaround is to recognize Chinese characters preceded or followed by a Latin character, and introduce a new split there, although I like the idea of automatically translating Traditional to Simplified Chinese at some level of the stack.

**Comment by elvisyjlin** [comment]
I vote for Chinese converting due to the following reasons:
* CoreNLP is designed for Simplified Chinese. There are some other segmentation issues with Traditional Chinese sentences.
* Compare the example above, "當我 上 傳 照片 到 instagram時" vs "当 我 上传 照片 到 instagram 时", not only the "instagram時" is a problem, but "上 傳" is also another one. "上 傳" means "upload", which shouldn't be split. In SC, "上传" is segmented perfeectly. There are many other cases like this in the synthetic sentences.

**Comment by elvisyjlin** [comment]
I've upload a new result in the same link https://goo.gl/PeoWuY
* `dataset.zh-tw.part0.v2.tt` is the Traditional Chinese dataset.
* `synthetic.zh-tw.part0.v2.tsv` is the synthetic sentences.

I convert each Traditional Chinese sentences into Simplified Chinese, segment them with Almond Tokenizer (CoreNLP), and then convert the segmented sentences back to Traditional Chinese. This method solved ill segmentation of English words preceded by Chinese Characters and succeeded by Chinese Characters.

**Comment by gcampax** [comment]
Mh, if we convert all inputs into Simplified Chinese at the tokenizer level, we don't need to convert back to Traditional for the dataset or synthetic sentences, and we can train a single model for both Simplified and Traditional.

**Comment by elvisyjlin** [comment]
Oh yes, you're right! I'll make it trained with Simplified Chinese.

**Comment by johnnychhsu** [comment]
Where should we add the translation code for the enum?
Is that something in 
https://github.com/Stanford-Mobisocial-IoT-Lab/genie-toolkit/blob/master/lib/dataset_augmenter.js?

**Comment by gcampax** [comment]
No it would likely be in lib/sentence-generator/index.js, the part where it loads thingpedia/dataset and combines primitives and construct templates. You might need a new file format though.

**Comment by johnnychhsu** [comment]
I think we can handle this in lib/i18n/tranditional_chinese. we can translate those terms in `postprocessSynthetic(sentence, program)`.
What do you think?

**Comment by johnnychhsu** [comment]
So in lib/sentence-generator/index.js, the grammar will take turn generate sentences according to the construct templates.
Maybe it would be more efficient if we translate somewhere before go into `postprocessSynthetic`, like during the process it generates? Where do you define how to handle type enum?

**Comment by elvisyjlin** [comment]
A complete Traditional Chinese dataset and synthesized tsv are available in the google drive. Thanks for Johnny's help.

**Comment by gcampax** [comment]
Closing this.
