### ISSUE TITLE
Entity Disambiguation Issues

### ISSUE THREAD

**Issue by ryachen01** [stanford-oval/genie-toolkit#314]
Songs, albums, and artists get frequently confused. 

Examples:

-  Play piano man

    - Plays the first song from the album - when it is ambiguous, it needs to play the song, and not the album.

- Play hey jude

   - Gets album "hey jude" by Wilson Pickett.

- Play maroon 5

   - Gets song Maroon 5 Medley.

**Comment by gcampax** [comment]
These all seem to be model issues (aka accuracy issues), which will be solved when we have [NER](https://wiki.almond.stanford.edu/nlp/ner) in the model. I'm going to leave this issue open for tracking, but I don't expect we'll have any change in genie-toolkit.

**Comment by gcampax** [comment]
These should all have been addressed by representing ambiguity explicitly in ThingTalk, and also adding Bootleg.
