### ISSUE TITLE
Shouldn't user location carry over in a dialogue?

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genie-toolkit#345]
In conversations like the following, the user has to provide the current location every time parser translates the query to `location:current_location`

> U: what is the weather like?
> A: Where are you now?
> U: stanford
> A: The cloudiness is 0.
> U: can you show me restaurants around here?
> A: Where are you now?

**Comment by gcampax** [comment]
Yes it should. This is a bug in how we handle `$context.location.current_location` in the agent. We should store for the current conversation.

**Comment by gcampax** [comment]
Will be fixed by #439
