### ISSUE TITLE
Is this suppose to be this.datadir instead of this.workdir?

### ISSUE THREAD

**Issue by johnnychhsu** [stanford-oval/genie-toolkit#36]
https://github.com/stanford-oval/genie-toolkit/blob/ed313bc5f90e7b0a4e041c40491421727a862033/lib/training/decanlp.js#L55

**Comment by gcampax** [comment]
No this.workdir is correct. `decanlp` expects the data directory to be in a certain format (namely, containing a subdirectory named after the task being trained). Genie will set it up by creating a symbolic link to the true data directory.
