### ISSUE TITLE
Specify min, max and scale of measurement units

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genie-toolkit#360]
Is there a way to specify minimum/maximum and scale of measurement units per property during dataset synthesis?
For example after running the Wikidata starter code (the artist domain), sentences like the following are generated:

> search an artist born on 9 milliseconds before now.

Or for a person's height km is used.

**Comment by gcampax** [comment]
I had missed this. But yeah you can specify `#[min_number]` and `#[max_number]` for measurement property. Eg you can say `#[min_number=1km]` and it won't generate anything less than that. Note though that numbers are placeholdered so this doesn't always work well: 1000 m is the same as 1 km but would show up as 13 m (aka NUMBER_0 m).

**Comment by gcampax** [comment]
This should be fixed since #492, as the augmentation code now honors min_number and max_number fully.
