### ISSUE TITLE
"a" in parameter values should not be removed

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genie-toolkit#440]
I encountered the following outputs (A and AT) by running `genie simulate-dialogs` on MultiWOZ. The agent utterance is "an and b guest house" which is probably the result of treating "a" inside the name as a stop word.

```
U: i am looking for a hotel to stay in .
UT: $dialogue @org.thingpedia.dialogue.transaction.execute;
UT: now => (@uk.ac.cam.multiwoz.Hotel.Hotel()), price_range == enum(expensive) => notify;
C: $dialogue @org.thingpedia.dialogue.transaction.execute;
C: @uk.ac.cam.multiwoz.Hotel.Hotel()
C: #[results=[
C:   { ... id="0"^^uk.ac.cam.multiwoz.Hotel:Hotel("a and b guest house"), ... },
...
C: #[count=33];
A: I have found an and b guest house or acorn guest house. All of them are moderate 4 star hotel.
AT: $dialogue @org.thingpedia.dialogue.transaction.sys_recommend_two;
```

**Comment by gcampax** [comment]
No, it's the result of synthetic postprocessing (auto grammar fix): we automatically transform "a" followed by a vowel into "an". We should not do that for names though.

**Comment by gcampax** [comment]
Synthetic postprocessing occurs before entity replacement now, so this is fixed.

**Comment by s-jse** [comment]
If postprocessing happens before entity replacement, does it mean agent utterances will say "I found **a** Applebee's" instead of "I found **an** Applebee's" since the article cannot be determined before parameter replacement?
