### ISSUE TITLE
Critical: help the user connect to an account

### ISSUE THREAD

**Issue by monicalam** [stanford-oval/genie-toolkit#450]
If the parse is "play a song", and no spotify is configured, the error message should be "To play a song, you need to connect to your Spotify account"  Do not say "configure a skill", this is jargon that sounds much harder than it seems.  In fact, the system should then initiate "configure a spotify account".  The same goes to IoT devices.  This kind of error reporting is cheap to do and makes a huge difference.

**Comment by gcampax** [comment]
Fixed by #452
