### ISSUE TITLE
Failed to switch icon after topic switch

### ISSUE THREAD

**Issue by rayslxu** [stanford-oval/genie-toolkit#470]
![image](https://user-images.githubusercontent.com/6879330/107815293-09795c80-6d28-11eb-82b6-a72aade1ba36.png)

**Comment by gcampax** [comment]
Oh the reason is that the first one is not a topic switch - the context is still Yelp, because "greet" is a dialogue act in the state machine, not a faq reply. The second one contains both Yelp and builtin, and Yelp wins over builtin because builtin has no icon. We need to fix that one.
