### ISSUE TITLE
Asking about weather didn't work

### ISSUE THREAD

**Issue by valkjsaaa** [stanford-oval/genie-toolkit#485]
<img width="731" alt="Screen Shot 2021-02-22 at 12 13 41 PM" src="https://user-images.githubusercontent.com/5488815/108766121-9a5eed80-7509-11eb-93a3-b1f70354ae31.png">

**Comment by gcampax** [comment]
This is related to #368, in the sense that certain questions (including clarifying questions about location) are handled outside the state machine and therefore one needs to reset (using [X]) or answer the question. You did neither of those things, and hit the bug.

**Comment by valkjsaaa** [comment]
ohh. I got it. It's kind of hard to understand what does the [x] means.
