### ISSUE TITLE
It seems that weather forecast is not working?

### ISSUE THREAD

**Issue by valkjsaaa** [stanford-oval/genie-toolkit#497]
<img width="670" alt="Screen Shot 2021-02-24 at 12 42 14 PM" src="https://user-images.githubusercontent.com/5488815/109063233-ca3efa00-769d-11eb-9bf8-fe5c1ec0160a.png">

I think the system returns the current weather when I'm asking weather for tomorrow.

**Comment by gcampax** [comment]
See https://github.com/stanford-oval/thingpedia-common-devices/issues/233
