### ISSUE TITLE
Commands without a device name should implicitly apply to all devices

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#540]
"Turn on the lights" should implicitly apply to all the lights, rather than pick one light at random, or ask the user which light to turn on.
I am not sure though if we should apply this to all devices, or this should be an annotation specified on the function/class to control this behavior.

**Comment by mrand** [comment]
Oddly enough, EVEN when I specify "turn off ALL the pool table lights", it will list out the lights and ask which I want. 
![image](https://user-images.githubusercontent.com/435987/113897521-91ac3900-9790-11eb-96bc-b859b03785ed.png)

**Comment by gcampax** [comment]
Which version of Almond did you test with? This issue is about Almond 2.0 (currently under development and available at dev.almond.stanford.edu or from our testing Hassio repository), which behaves quite differently in this respect from Almond 1.8 (latest stable version).
