### ISSUE TITLE
Cloud sync failing on the cloud side

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genie-toolkit#656]
```
(node:441) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at /opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/db/syncdb.js:255:62
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
HTTP request failed: 404 page not found
Processing syncdb change for device failed HTTPError: Unexpected HTTP error 404 in request to http://dbproxy.staging.svc.cluster.local:8200/synctable/user_device/623/io.home-assistant%2Fhttp%3A%2F%2F127.0.0.1%3A8123/1623713798444
    at IncomingMessage.<anonymous> (/opt/almond-cloud/node_modules/thingpedia/dist/helpers/http.js:139:35)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 404,
  url: 'http://dbproxy.staging.svc.cluster.local:8200/synctable/user_device/623/io.home-assistant%2Fhttp%3A%2F%2F127.0.0.1%3A8123/1623713798444',
  detail: '404 page not found'
}
```

This is causing Travis to hang because the connection is dropped incorrectly by the cloud.

**Comment by gcampax** [comment]
On a different user, I'm seeing this error:
```
(node:343) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at /opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/db/syncdb.js:255:62
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gcampax** [comment]
> On a different user, I'm seeing this error:
> 
> ```
> (node:343) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
>     at /opt/almond-cloud/node_modules/genie-toolkit/dist/lib/engine/db/syncdb.js:255:62
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Oh this error is very cryptic but it occurs because the type of data returned by the /sync endpoint is not a tuple with three values, it's an object with three properties.

**Comment by jgd5** [comment]
dbproxy is decoding the uri escaped components: 

[GIN] 2021/06/14 - 23:36:38 | 404 |         966ns |   172.31.42.214 | POST     "/synctable/user_device/623/io.home-assistant/http://127.0.0.1:8123/1623713798444"

I just submitted a PR to disable this default behavior.

**Comment by gcampax** [comment]
This was fixed.
