### ISSUE TITLE
(Production) Reminder requests conflated with Yelp lookups 

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/genie-toolkit#697]
Step 1: can you tell me a good japanese restaurant
Genie: I see Odori Japanese Cuisine, Taro San Japanese Noodle Bar, and YAYOI. They're moderate restaurants rated 3.5 star.

Step 2: can you remind me to take a break every hour?
Genie: Alright, I will get restaurants that have Japanese food every 1 min.

[log-web-74c21970.txt](https://github.com/stanford-oval/genie-toolkit/files/6827707/log-web-74c21970.txt)

**Comment by gcampax** [comment]
I believe this was fixed given recent changes to the model.
