### ISSUE TITLE
Enhancement request - Clear Logging or other workaround

### ISSUE THREAD

**Issue by tonyespinoza1** [stanford-oval/genie-toolkit#710]
If there were a way to clear my local log I would do so between each session so I could isolate the relevant bits to include when filing an issue here.

I'm sure there are other workarounds, so just let me know if there's a fast way to grab the log of the most immediate session.  Right now I am careful to use keywords in each session that are unique so I can search quickly.  

At stake here is the speed of bug reporting and, more importantly, my accuracy in uploading the correct logging info.  :)

**Comment by gcampax** [comment]
Since #719 the logs are sorted correctly, and the new session is at the end. Is that sufficient?

**Comment by tonyespinoza1** [comment]
yes, absolutely!

**Comment by tonyespinoza1** [comment]
btw, just tried this on Staging and it didn't append my latest to the bottom of the log, but perhaps the change has not been pushed yet.

**Comment by gcampax** [comment]
Yeah I had not closed this issue because I haven't deployed the fix yet. I will do that once other concurrent changes are behaving...

**Comment by gcampax** [comment]
Fix is deployed, and the conversations are sorted now. Closing.
