### ISSUE TITLE
Unable to download the parameter dataset

### ISSUE THREAD

**Issue by Shisir99** [stanford-oval/genie-toolkit#866]
$genie download-entity-values -d parameter-datasets/ --manifest parameter-datasets.tsv
the above command is working fine but the latter one is giving error.
$genie download-string-values -d parameter-datasets/ --manifest parameter-datasets.tsv --append-manifest

I have the developer key, but don't know where to use the developer key.

Error: 
HTTPError: Unexpected HTTP error 400 in request to https://thingpedia.stanford.edu/thingpedia/api/v3/strings/list/campusplan.kit.advanced:place?locale=en-US&thingtalk_version=2.1.0
    at IncomingMessage.<anonymous> (/home/shishirkumar/genie-toolkit/node_modules/thingpedia/dist/helpers/http.js:142:35)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 400,
  url: 'https://thingpedia.stanford.edu/thingpedia/api/v3/strings/list/campusplan.kit.advanced:place?locale=en-US&thingtalk_version=2.1.0',
  detail: `<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Genie - Error</title><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i"><link rel="stylesheet" href="https://almond-static.stanford.edu/assets/stylesheets/bootstrap.min.css"><link rel="stylesheet" href="https://almond-static.stanford.edu/assets/stylesheets/style.css"><script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script><script src="https://almond-static.stanford.edu/assets/javascripts/validator.min.js"></script><script src="https://almond-static.stanford.edu/assets/javascripts/jstz.min.js"></script><script src="https://almond-static.stanford.edu/assets/javascripts/shared.js"></script></head><body data-icon-cdn="https://almond-static.stanford.edu" data-locale="en-US" data-thingpedia-url="/thingpedia" data-nl-server-url="https://nlp.almond.stanford.edu" data-voice-server-url="https://voice.almond.stanford.edu"><nav class="navbar-default navbar navbar-fixed-top" role="banner"><div class="navbar-header"><button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#page-nav"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand hidden-xs hidden-sm" href="/"><!--img.logo_top(src=Config.ASSET_CDN + '/images/almond.png')--><span>Genie</span></a><span class="navbar-brand hidden-md hidden-lg" aria-hidden="true">Error</span></div><div class="navbar-collapse collapse" role="navigation" id="page-nav"><ul class="nav navbar-nav"><li class="hidden-md hidden-lg hidden-sm"><a href="/">Home</a></li><li><a href="https://oval.cs.stanford.edu">OVAL Lab</a></li><li><a href="/thingpedia">Thingpedia</a></li><li><a href="https://wiki.almond.stanford.edu">Docs</a></li></ul><ul class="nav navbar-nav navbar-right"><li><a class="navbar-login" id="navbar-login-button" href="/user/login">Log In</a></li></ul></div></nav><div class="container" id="page-body"><div class="row hidden-xs hidden-sm"><h1 class="col-sm-12" id="page-title">Error</h1></div><div class="row"><div class="col-sm-12"><div class="msg-container"><div class="msg-left-block"><img class="msg-image" src="https://almond-static.stanford.edu/assets/images/almond_error.png"></div><div class="msg-right-block"><div class="msg-title"><h2 class="p">Sorry that did not work</h2></div><div class="msg-body"><h3 class="p">Missing or invalid parameter developer_key</h3></div></div></div><div class="msg-button"><a class="btn btn-primary custom-btn" href="javascript:history.back()">Go back</a></div></div></div></div><footer class="page-footer hidden-xs hidden-sm"><div class="container"><div class="row"><div class="col-xs-12"><p><small>Genie is part of a research project of the <a href='https://oval.cs.stanford.edu'>Open Virtual Assistant Lab</a> at Stanford University.</small></p><p><small><a href="/about/tos">Terms of Service</a> -\n` +
    '<a href="/about/privacy">Privacy Policy</a> -\n' +
    '<span class="footer-icons"><a class="social-icon" href="https://twitter.com/StanfordOVAL"><img src="https://almond-static.stanford.edu/assets/images/symbolic-logo-twitter.svg" title="Connect with us on Twitter"></a><span class="social-icon-spacer" role="presentation"></span><a class="social-icon" href="https://discord.gg/anthtR4"><img src="https://almond-static.stanford.edu/assets/images/symbolic-logo-discord.svg" title="Join us on Discord"></a><span class="social-icon-spacer" role="presentation"></span><a class="social-icon" href="https://community.almond.stanford.edu/"><img src="https://almond-static.stanford.edu/assets/images/symbolic-logo-community.svg" title="Join our Community"></a><span class="social-icon-spacer" role="presentation"></span><a class="social-icon" href="https://github.com/stanford-oval"><img src="https://almond-static.stanford.edu/assets/images/symbolic-logo-github.svg" title="Fork me on GitHub"></a><span class="social-icon-spacer" role="presentation"></span><a class="social-icon" href="mailto:thingpedia-admins@lists.stanford.edu"><img src="https://almond-static.stanford.edu/assets/images/symbolic-logo-email.svg" title="Contact us via email"></a></span></small></p></div></div></div></footer></body></html>'
}

**Comment by gcampax** [comment]
You can set the developer in the git config with `git config thingpedia.developer-key abcdef...`, or you can pass it on the commandline with `--developer-key abcdef...`
